<a href="https://colab.research.google.com/github/mikachan400/carisurg-portfolio-week-0/blob/main/Week0_Tutorial1_Cleaning_Gender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv('EmergencyTriageDataset_Reduced_Dirty.csv')
df.head()

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0

In [10]:
df['Gender'].unique()
df['Gender'].value_counts()

Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [11]:
gender_map = {
    'Male': 1,
    'MALE': 1,
    '1': 1,
    'Female': 0,
    'FEMALE': 0,
    '0': 0
}

In [13]:
df['Gender_Clean'] = df['Gender'].map(gender_map)

In [14]:
df['Gender_Clean'].value_counts()
df['Gender_Clean'].isnull().sum()

np.int64(0)

In [15]:
df = df.drop(columns=['Gender'])
df = df.rename(columns={'Gender_Clean': 'Gender'})

In [16]:
df.head()
df['Gender'].value_counts()

Gender
1    1176
0    1029
Name: count, dtype: int64

In [19]:
df.head()

   ID  Age   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2  Gender
0   1   34  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0       0
1   2   20  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0       1
2   3   77  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0       0
3   4   23   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0       0
4   5   86  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0       0

In [24]:
df.to_csv('EmergencyTriageDataset_Reduced_Clean.csv', index=False)